telemetry:
  disable_telemetry_sharing: false

replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI
      sslmode: verify-full

storage:
  type: postgresql
  uri: !env PS_STORAGE_SOURCE_URI
  sslmode: disable

port: !env PS_PORT

sync_config:
  path: sync-config.yaml

client_auth:
  jwks_uri: !env PS_JWKS_URI
  audience: ['authenticated']
