config:
  edition: 3

streams:
  store_data:
    auto_subscribe: true
    queries:
      - SELECT * FROM store_staff WHERE user_id = auth.user_id()
      - SELECT stores.* FROM stores
        INNER JOIN store_staff ON store_staff.store_id = stores.id
        WHERE store_staff.user_id = auth.user_id()
      - SELECT products.* FROM products
        INNER JOIN inventory_levels ON inventory_levels.product_id = products.id
        INNER JOIN store_staff ON store_staff.store_id = inventory_levels.store_id
        WHERE store_staff.user_id = auth.user_id()
      - SELECT inventory_levels.* FROM inventory_levels
        INNER JOIN store_staff ON store_staff.store_id = inventory_levels.store_id
        WHERE store_staff.user_id = auth.user_id()
      - SELECT categories.* FROM categories
        INNER JOIN store_staff ON store_staff.user_id = auth.user_id()
      - SELECT sales.* FROM sales
        INNER JOIN store_staff ON store_staff.store_id = sales.store_id
        WHERE store_staff.user_id = auth.user_id()
      - SELECT sale_lines.* FROM sale_lines
        INNER JOIN sales ON sales.id = sale_lines.sale_id
        INNER JOIN store_staff ON store_staff.store_id = sales.store_id
        WHERE store_staff.user_id = auth.user_id()
