-- Shared catalog + per-location inventory levels, payment method toggles,
-- and Paymongo QR as a sale payment method.

-- ---------------------------------------------------------------------------
-- inventory_levels
-- Client inserts (PowerSync) supply id; identity fills SQL-only rows.
-- ---------------------------------------------------------------------------

create table public.inventory_levels (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products (id) on delete cascade,
  store_id uuid not null references public.stores (id) on delete cascade,
  qty numeric(12, 3) not null default 0 check (qty >= 0),
  unique (product_id, store_id)
);

create index inventory_levels_store_id_idx on public.inventory_levels (store_id);
create index inventory_levels_product_id_idx on public.inventory_levels (product_id);

insert into public.inventory_levels (product_id, store_id, qty)
select id, store_id, stock_qty
from public.products;

grant select, insert, update, delete on public.inventory_levels to authenticated, service_role;
grant select on public.inventory_levels to powersync_role;

do $$
declare
  seq_name text;
begin
  seq_name := pg_get_serial_sequence('public.inventory_levels', 'id');
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated, service_role', seq_name);
  end if;
end $$;

alter table public.inventory_levels enable row level security;

create policy "staff read store inventory levels"
  on public.inventory_levels for select to authenticated
  using (
    store_id in (select store_id from public.store_staff where user_id = auth.uid())
  );

create policy "staff insert store inventory levels"
  on public.inventory_levels for insert to authenticated
  with check (
    store_id in (select store_id from public.store_staff where user_id = auth.uid())
  );

create policy "staff update store inventory levels"
  on public.inventory_levels for update to authenticated
  using (
    store_id in (select store_id from public.store_staff where user_id = auth.uid())
  )
  with check (
    store_id in (select store_id from public.store_staff where user_id = auth.uid())
  );

create policy "staff delete store inventory levels"
  on public.inventory_levels for delete to authenticated
  using (
    store_id in (select store_id from public.store_staff where user_id = auth.uid())
  );

alter publication powersync add table public.inventory_levels;

-- ---------------------------------------------------------------------------
-- Destore products (catalog)
-- ---------------------------------------------------------------------------

drop policy "staff read store products" on public.products;
drop policy "staff update store products" on public.products;
drop policy "staff insert store products" on public.products;

drop index if exists public.products_store_id_idx;

alter table public.products drop column store_id;
alter table public.products drop column stock_qty;

create or replace function public.is_any_store_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.store_staff
    where user_id = auth.uid()
      and role = 'admin'
  );
$$;

revoke all on function public.is_any_store_admin() from public;
grant execute on function public.is_any_store_admin() to authenticated, service_role;

create policy "staff read catalog products"
  on public.products for select to authenticated
  using (
    exists (
      select 1
      from public.inventory_levels il
      where il.product_id = products.id
        and il.store_id in (select store_id from public.store_staff where user_id = auth.uid())
    )
  );

create policy "staff update catalog products"
  on public.products for update to authenticated
  using (
    exists (
      select 1
      from public.inventory_levels il
      where il.product_id = products.id
        and il.store_id in (select store_id from public.store_staff where user_id = auth.uid())
    )
  )
  with check (
    exists (
      select 1
      from public.inventory_levels il
      where il.product_id = products.id
        and il.store_id in (select store_id from public.store_staff where user_id = auth.uid())
    )
  );

create policy "admins insert catalog products"
  on public.products for insert to authenticated
  with check (public.is_any_store_admin());

-- ---------------------------------------------------------------------------
-- Destore categories (catalog-scoped)
-- ---------------------------------------------------------------------------

drop trigger if exists stores_seed_rice_category on public.stores;
drop function if exists public.seed_rice_category_for_store();

-- Collapse duplicate Rice presets onto the oldest row.
do $$
declare
  keep_id uuid;
begin
  select id into keep_id
  from public.categories
  where slug = 'rice'
  order by created_at, id
  limit 1;

  if keep_id is not null then
    update public.products
    set category_id = keep_id
    where category_id in (select id from public.categories where slug = 'rice')
      and category_id is distinct from keep_id;

    delete from public.categories
    where slug = 'rice'
      and id is distinct from keep_id;
  end if;
end $$;

drop policy "staff read store categories" on public.categories;
drop policy "staff insert store categories" on public.categories;
drop policy "staff update store categories" on public.categories;
drop policy "staff delete store categories" on public.categories;

alter table public.categories drop constraint if exists categories_store_id_slug_key;
drop index if exists public.categories_store_id_idx;

alter table public.categories drop column store_id;

alter table public.categories
  add constraint categories_slug_key unique (slug);

insert into public.categories (name, slug)
select 'Rice', 'rice'
where not exists (select 1 from public.categories where slug = 'rice');

create policy "staff read catalog categories"
  on public.categories for select to authenticated
  using (
    exists (select 1 from public.store_staff where user_id = auth.uid())
  );

create policy "staff insert catalog categories"
  on public.categories for insert to authenticated
  with check (
    exists (select 1 from public.store_staff where user_id = auth.uid())
  );

create policy "staff update catalog categories"
  on public.categories for update to authenticated
  using (
    exists (select 1 from public.store_staff where user_id = auth.uid())
  )
  with check (
    exists (select 1 from public.store_staff where user_id = auth.uid())
  );

create policy "staff delete catalog categories"
  on public.categories for delete to authenticated
  using (
    exists (select 1 from public.store_staff where user_id = auth.uid())
      and (slug is distinct from 'rice')
  );

-- ---------------------------------------------------------------------------
-- Payment methods
-- ---------------------------------------------------------------------------

alter table public.stores
  add column payment_methods jsonb not null default '{"cash": true, "gcash": true, "paymongo_qr": false}'::jsonb;

create policy "admins update assigned stores"
  on public.stores for update to authenticated
  using (public.is_store_admin(id))
  with check (public.is_store_admin(id));

alter table public.sales drop constraint if exists sales_payment_method_check;
alter table public.sales add constraint sales_payment_method_check
  check (payment_method in ('cash', 'gcash', 'paymongo_qr'));
